@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (Level 2 - Process View) - US 370
autonumber

participant "MD" as MD <<system (C4)>>

?o-> MD : PATCH (.../devices/:code)
activate MD

<-- MD : status: 200/404
deactivate MD

@enduml