@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (Level 1 - Process View) - US 290
autonumber

participant "RobDroneGo" as Sistema <<system (C4)>>

?o-> Sistema : GET (.../buildings/:code/elevators)
activate Sistema

<-- Sistema : status: 200/404
deactivate Sistema

@enduml