@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (Level 2 - Process View) - US 1030
autonumber

Actor "Fleet Manager" as manager
participant "UI" as UI <<system (C4)>>
participant "MD" as MD <<system (C4)>>

activate manager
    manager -> UI : Ask to list devices
    activate UI

        UI -> MD : GET (.../devices)
        activate MD
            UI <-- MD : status: 200/404
        deactivate MD

        UI --> manager : Success / Error
    deactivate UI
deactivate manager

@enduml