@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (Level 1 - Process View) - US 1080
autonumber

Actor "Campus Manager" as campusManager
participant "RobDroneGo WebApp" as WebSite <<system (C4)>>
participant "RobDroneGo" as Sistema <<system (C4)>>

activate campusManager
    campusManager -> WebSite : Ask to list buildings with number floors between min and max
    activate WebSite
        WebSite --> campusManager : Ask to insert min and max
    deactivate WebSite

    campusManager -> WebSite : Insert min and max
    activate WebSite
        WebSite -> Sistema : GET (.../buildings?min=:min&max=:max)
        activate Sistema
            WebSite <-- Sistema : status: 200/404
        deactivate Sistema

        WebSite --> campusManager : Success / Error
    deactivate WebSite
deactivate campusManager

@enduml
