@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (Level 1 - Process View) - US 190
autonumber

participant "RobDroneGo" as Sistema <<system (C4)>>

?o-> Sistema : POST (.../buildings/floors)
activate Sistema

<-- Sistema : status: 201/400
deactivate Sistema

@enduml