@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (Level 1 - Process View) - US 350
autonumber

actor "Fleet Manager" as Gestor
participant "RobDroneGo" as Sistema <<system (C4)>>

    activate Gestor
    Gestor -> Sistema : POST (.../devices/types)
    activate Sistema

    Gestor <-- Sistema : status: 201/400
    deactivate Sistema

deactivate Gestor

@enduml