@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Sequence Diagram (Level 3 - Process View) - US 240
autonumber

participant "BE" as BE <<system (C4)>>
participant "BD" as BD <<system (C4)>>

?o-> BE : POST (.../buildings/passageways)
activate BE

    BE --> BD : Verify building and floors exists
    activate BD
    BD --> BE :
    deactivate BD

    BE --> BD : Insert passageway
    activate BD
    BD --> BE :
    deactivate BD

<-- BE : status: 201/400
deactivate BE

@enduml