@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Sequence Diagram (Level 3 - Process View) - US 250
autonumber

participant "BE" as BE <<system (C4)>>
participant "BD" as BD <<system (C4)>>

?o-> BE : PUT/PATCH (.../buildings/passageways/:passagewayCode)
activate BE

    BE --> BD : Verify passageway exists
    activate BD
    BD --> BE :
    deactivate BD

    BE --> BD : Update passageway
    activate BD
    BD --> BE :
    deactivate BD

<-- BE : status: 200/400
deactivate BE

@enduml