@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (Level 2 - Process View) - US 460 - Surveillance Task
autonumber

Actor "User" as user
participant "UI" as UI <<system (C4)>>

activate user
    user -> UI : Ask to request a surveillance task
    activate UI
        UI -> : GET (../api/buildings)
        UI <-- : status: 200/404
        
        UI -> : GET (.../api/me)
        UI <-- : status: 200/404

        UI --> user : List buildings and ask to choose one
    deactivate UI

    user -> UI : Choose one building
    activate UI
        UI -> : GET (.../api/buildings/:code/floors)
        UI <-- : status: 200/404

        UI --> user : List building floors and ask to choose one or more
    deactivate UI

    user -> WebSite : Choose one or more floors
    activate WebSite
        WebSite --> user : Ask to insert the emergency contact name
    deactivate WebSite

    user -> WebSite : Insert the emergency contact name
    activate WebSite
        WebSite --> user : Ask to insert the emergency contact phone number
    deactivate WebSite

    user -> WebSite : Insert the emergency contact phone number
    activate UI
        UI -> : POST (.../api/tasks/surveillances)
        UI <-- : status: 201/400

        UI --> user : Task created / Data error
    deactivate UI
deactivate user

@enduml
