@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Sequence Diagram (Level 3 - Process View - UI) - US 470
autonumber

participant "View" as View <<Component>>
participant "Component" as Component <<Component>>
participant "Model" as Model <<Component>>
participant "Service" as Service <<Component>>

?o-> View : Ask to consult pending requests for a task type
activate View
    View -> Component : onTaskTypeChange()
    activate Component
        activate Service
            alt pickup and delivery task
                Component -> Service : getPickupAndDeliveryTask()
                Service -> : GET (.../tasks/deliveries/requesteds)
            else surveillance task
                Component -> Service : getSurveillanceTasks()
                Service -> : GET (.../tasks/surveillances/requesteds)
            end
            Service <--: status: 200/404
            Service --> Component : Success / Error
        deactivate Service

        Component --> View : Information about the success/error
    deactivate Component
<-- View : Ask to choose a request and the action to take
deactivate View

?o-> View : Choose the request and approve or refuse
activate View
    View -> Component : performTaskAction()
    activate Component
        Component --> Model** :
        Component -> Service : approveRejectTask(user)
        activate Service
            alt pickup and delivery task
               alt approve
                   Service -> : PATCH (.../tasks/deliveries/:code/approve)
               else reject
                  Service -> : PATCH (.../tasks/deliveries/:code/reject)
               end
            else surveillance task
              alt approve
                  Service -> : PATCH (.../tasks/surveillances/:code/approve)
              else reject
                 Service -> : PATCH (.../tasks/surveillances/:code/reject)
              end
            end
            Service <--: status: 200/404
            Service --> Component : Success / Error
        deactivate Service

        Component --> View : Information about the success/error
    deactivate Component
<-- View : Request approved or refused/data error
deactivate View

@enduml