@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (Level 1 - Process View) - US 480
autonumber

Actor "System Manager" as SystemManager
participant "RobDroneGo" as Sistema <<system (C4)>>

activate SystemManager
    SystemManager -> Sistema : Ask to view tasks not approved
    activate Sistema

    Sistema --> SystemManager : asks to select task type (delivery or surveillance tasks)
    deactivate Sistema

    SystemManager -> Sistema : selects task type
    activate Sistema

    Sistema --> SystemManager : shows select task type list
    deactivate Sistema

deactivate SystemManager

@enduml
