@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (Level 1 - Process View) - US 1050
autonumber

Actor "Campus Manager" as campusManager
participant "RobDroneGo WebApp" as WebSite <<system (C4)>>
participant "RobDroneGo" as Sistema <<system (C4)>>

activate campusManager
    campusManager -> WebSite : Ask to create building
    activate WebSite
        WebSite --> campusManager : Ask to insert data
    deactivate WebSite

    campusManager -> WebSite : Insert data
    activate WebSite
        WebSite -> Sistema : POST (.../buildings)
        activate Sistema
            WebSite <-- Sistema : status: 201/400
        deactivate Sistema

        WebSite --> campusManager : Success / Error
    deactivate WebSite
deactivate campusManager

@enduml
