@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Sequence Diagram (Level 3 - Process View - UI) - US 1070
autonumber

participant "View" as View <<Component>>
participant "Component" as Component <<Component>>
participant "Model" as Model <<Component>>
participant "Service" as Service <<Component>>

?o-> View : Ask to edit bulding
activate View
    View -> Component : getAllBuildings()
    activate Component
        Component -> Service : getAllBuildingsInfo()
        activate Service
            Service -> : GET (.../buildings)
            Service <--: status: 200/404
            Service --> Component : Success / Error
        deactivate Service

        Component --> View : Information about the success/error
    deactivate Component
<-- View : Ask to choose an building and to edit data
deactivate View

?o-> View : Choose the building and edit
activate View
    View -> Component : editBuilding()
    activate Component
        Component --> Model** :
        Component -> Service : updateBuilding(building)
        activate Service
            Service -> : PUT/PATCH (.../buildings/:code)
            Service <--: status: 200/404
            Service --> Component : Success / Error
        deactivate Service

        Component --> View : Information about the success/error
    deactivate Component
<-- View : Building edited/data error
deactivate View

@enduml
