@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (Level 2 - Process View) - US 1070
autonumber

participant "UI" as UI <<system (C4)>>
participant "MD" as MD <<system (C4)>>

?o-> UI : Ask to edit bulding
activate UI

    UI -> MD : GET (.../buildings)
    activate MD
        UI <-- MD : status: 200/404
    deactivate MD

<-- UI : : Ask to choose an building and to edit data
deactivate UI

?o-> UI : Choose the building and edit
activate UI

    UI -> MD : PUT/PATCH (.../buildings/:code)
    activate MD
        UI <-- MD : status: 200/404
    deactivate MD

<-- UI : Building edited/data error
deactivate UI

@enduml
