@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (Level 1 - Process View) - US 20
autonumber

Actor "System Manager" as SystemManager
participant "RobDroneGo" as Sistema <<system (C4)>>

activate SystemManager
    SystemManager -> Sistema : Ask to register user
    activate Sistema

    Sistema --> SystemManager : Ask to insert data
    deactivate Sistema

    SystemManager -> Sistema : Insert user data
    activate Sistema

    Sistema --> SystemManager : User created/data error
    deactivate Sistema
deactivate SystemManager

@enduml