@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (Level 2 - Process View) - US 200
autonumber

participant "MD" as MD <<system (C4)>>

?o-> MD : PUT/PATCH (.../buildings/:code/floors/:code)
activate MD

<-- MD : status: 200/400
deactivate MD

@enduml