@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (Level 3 - Process View) - US 150
autonumber

participant "buildingRoute" as route <<Route>>
participant "ctrlPassageway :\n IPassagewayController" as controller <<Controller>>
participant "passagewayServiceInstance :\n IPassagewayService" as service <<Service>>
participant "passagewayRepo :\n IPassagewayRepository" as repo <<Repository>>
participant "DB Driver" as db <<DataBase>>

participant "allPassageway :\n passageway" as allPassageways <<Domain>>
participant "passagewaysDTO :\n IPassagewayDTO" as passagewaysDTO <<DTO>>

?o-> route : GET (.../passageways?building_1=:building_1&building_2=building_2)
activate route
    route -> controller : execute(req, res, next)
    activate controller
        controller -> controller : getPassagewaysBetweenBuildings(req, res, next)
        activate controller
            controller -> service : getPassagewaysBetweenBuildings(building_1?, building_2?)

            activate service
                service -> repo : findAllPassageways(building_1?, building_2?)
                activate repo
                    repo -> db :
                    activate db
                        db --> repo :
                    deactivate db
                    repo --> service : allPassageways
                deactivate repo
                service --> controller : passagewaysDTO
            deactivate service

            controller --> controller : status: 200/404
        deactivate controller
        controller --> route : status: 200/404
    deactivate controller

    <-- route : status: 200/404
deactivate route

@enduml