@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Sequence Diagram (Level 3 - Process View) - US 260
autonumber

participant "BE" as BE <<system (C4)>>
participant "BD" as BD <<system (C4)>>

?o-> BE : GET (.../passageways?building_1=:building_1&building_2=building_2)
activate BE

    BE --> BD : Select passageway with or without building_1 and building_2
    activate BD
        BD --> BE :
    deactivate BD

<-- BE : status: 200/404
deactivate BE

@enduml