@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (Level 2 - Process View) - US 270
autonumber

participant "MD" as MD <<system (C4)>>

?o-> MD : POST (.../buildings/elevators)
activate MD

<-- MD : status: 201/400
deactivate MD

@enduml